### PR TITLE
Add stale action for issues

### PR DESCRIPTION
**Pull request by Andre601**
Adds `actions/stale` for handling stale issues.

I've included it in the workflow file containing the lock action.
I also disabled (commented out) the lock action, as it seems to encounter rate limits (Probs bad rate limit handling on the action's end?).

May re-enable it later, or see if a lock option can be implemented to the stale action itself. Issue for that can be tracked here: https://github.com/actions/stale/issues/1188

### CODE REVIEW

**Review by LoneDev6 — CHANGES_REQUESTED** [review]
I think it should be changed to this.
Basically no message to avoid useless notifications. In some cases I might be the one ignoring issues to prioritize others and I don't want people to get notified about that.
Also I disabled automatic close.
What do you think?
```yml
name: 'Lock Threads'

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write
  discussions: write

concurrency:
  group: lock-threads

jobs:
  label-inactive-issues:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: "Label inactive Issues"
        uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-label: "status: inactive"
          days-before-stale: 90
          days-before-close: -1
          days-before-pr-stale: -1 # Ignore Pull requests
```

**Comment by Andre601** [comment]
Idk... Having issues marked as stale without anything else seems pointless in the end. Especially if nobody is even aware it became stale.
Because in that case can we just not have the action to begin with. Would be basically the same result.

**Comment by Andre601** [comment]
I implemented your requested changes.
I personally am not a fan of this, but at the end is it not my decision to make here. Only thing left is have the label made before merge (unless the action would create it which afaik is not the case)

**Comment by TheGiraffe3** [comment]
That is correct. The label will not automatically be created.

**Pull request closed without merging**
